name: Backend CI

on:
  push:
    branches: [main, develop]
    paths: ['server/**']
  pull_request:
    branches: [main]
    paths: ['server/**']

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        
    - name: Run tests
      working-directory: ./server
      env:
        PYTHONPATH: ${{ github.workspace }}/server
        DEBUG_MODE: false
        ENHANCED_JD_NORMALIZATION: true
      run: |
        python -m pytest tests/ -v --tb=short
        
    - name: Test Docker build
      working-directory: ./server
      run: |
        docker build -t tailor-flow-api .
        
    - name: Test health endpoint
      working-directory: ./server
      run: |
        docker run -d -p 8000:8000 --name test-api tailor-flow-api
        sleep 10
        curl -f http://localhost:8000/api/health
        docker stop test-api